export const PATH_TAB_LIST = 'list'
export const PATH_TAB_LOCATION = 'location'

export const PATH_PAGE_PROFILE = '/profile/:uid'
export const PATH_PAGE_SEARCH = '/search'
export const PATH_PAGE_OFFERS = '/offers/:userId'
export const PATH_PAGE_REGISTRATION = '/registration'
export const PATH_PAGE_GAME = '/game/:gameId'
export const PATH_PAGE_CHATS = '/chats'
export const PATH_PAGE_CHAT = '/chats/:chatId'
export const PATH_PAGE_DEAL = '/deals/:chatId'